# Generated by Django 4.2.1 on 2023-06-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movielist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatchlistItem',
            new_name='Watchlist',
        ),
    ]
